// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANoEtE2olgSKLgD2wRSEh8wHtPvRgkVP8',
    appId: '1:214602559549:web:947a2e51d0c6c632613a54',
    messagingSenderId: '214602559549',
    projectId: 'devgram-c4e6b',
    authDomain: 'devgram-c4e6b.firebaseapp.com',
    storageBucket: 'devgram-c4e6b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB22H6a6oi1peDdfjAO45zWc640hI12x_M',
    appId: '1:214602559549:android:817a1e25a02b6645613a54',
    messagingSenderId: '214602559549',
    projectId: 'devgram-c4e6b',
    storageBucket: 'devgram-c4e6b.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANoEtE2olgSKLgD2wRSEh8wHtPvRgkVP8',
    appId: '1:214602559549:web:3b3a47f26cd5ad07613a54',
    messagingSenderId: '214602559549',
    projectId: 'devgram-c4e6b',
    authDomain: 'devgram-c4e6b.firebaseapp.com',
    storageBucket: 'devgram-c4e6b.firebasestorage.app',
  );
}
